# Generated by Django 6.1.1 on 2026-09-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_alter_employee_dept_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
